2019-04-10 18:34:35,960 ERROR: Unhandled Exception: No content, file name. Nothing is given [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:34:53,555 ERROR: Unhandled Exception: No content, file name. Nothing is given [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:35:13,763 ERROR: Unhandled Exception: No content, file name. Nothing is given [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:36:32,260 ERROR: Unhandled Exception: No content, file name. Nothing is given [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:37:03,078 ERROR: Unhandled Exception: No content, file name. Nothing is given [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:37:54,780 ERROR: Unhandled Exception: No content, file name. Nothing is given [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:41:26,597 ERROR: Unhandled Exception: Worksheet titles must be unicode [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:42:09,594 ERROR: Unhandled Exception: Worksheet titles must be unicode [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:43:07,000 ERROR: Exception on /excel [GET] [in /home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-04-10 18:43:07,001 ERROR: Unhandled Exception: The view function did not return a valid response. The function either returned None or ended without a return statement. [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 18:44:58,285 ERROR: Exception on /excel [GET] [in /home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/cry/PycharmProjects/ns-gas/venv/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-04-10 18:44:58,285 ERROR: Unhandled Exception: The view function did not return a valid response. The function either returned None or ended without a return statement. [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:05:03,197 ERROR: Unhandled Exception: int() argument must be a string or a number, not 'NoneType' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:05:26,053 ERROR: Unhandled Exception: int() argument must be a string or a number, not 'NoneType' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:05:40,878 ERROR: Unhandled Exception: int() argument must be a string or a number, not 'NoneType' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:05:50,084 ERROR: Unhandled Exception: int() argument must be a string or a number, not 'NoneType' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:06:48,526 ERROR: Unhandled Exception: filter must be an instance of dict, bson.son.SON, or other type that inherits from collections.Mapping [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:06:59,886 ERROR: Unhandled Exception: filter must be an instance of dict, bson.son.SON, or other type that inherits from collections.Mapping [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:07:20,824 ERROR: Unhandled Exception: filter must be an instance of dict, bson.son.SON, or other type that inherits from collections.Mapping [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:07:46,848 ERROR: Unhandled Exception: filter must be an instance of dict, bson.son.SON, or other type that inherits from collections.Mapping [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:07:58,014 ERROR: Unhandled Exception: filter must be an instance of dict, bson.son.SON, or other type that inherits from collections.Mapping [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:08:26,747 ERROR: Unhandled Exception: filter must be an instance of dict, bson.son.SON, or other type that inherits from collections.Mapping [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-10 19:08:35,831 ERROR: Unhandled Exception: filter must be an instance of dict, bson.son.SON, or other type that inherits from collections.Mapping [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:04:03,325 ERROR: Unhandled Exception: 'APP_ID' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:04:27,832 ERROR: Unhandled Exception: 'APP_ID' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:04:31,183 ERROR: Unhandled Exception: 'APP_ID' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:04:49,477 ERROR: Unhandled Exception: Please provide app_id and app_secret parameters in the construction of class. [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:05:11,616 ERROR: Unhandled Exception: Please provide app_id and app_secret parameters in the construction of class. [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:06:19,814 ERROR: Unhandled Exception: Please provide app_id and app_secret parameters in the construction of class. [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:07:06,214 ERROR: Unhandled Exception: Please provide app_id and app_secret parameters in the construction of class. [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:28:59,963 ERROR: Unhandled Exception: unbound method access_token() must be called with WeixinLogin instance as first argument (got unicode instance instead) [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:29:20,963 ERROR: Unhandled Exception: unbound method access_token() must be called with WeixinLogin instance as first argument (got unicode instance instead) [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:31:30,565 ERROR: Unhandled Exception: 'dict' object has no attribute 'errcode' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:31:56,812 ERROR: Unhandled Exception: 'dict' object has no attribute 'errcode' [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:32:14,306 ERROR: Unhandled Exception: 41002 appid missing, hints: [ req_id: PhfBg6yFe-Yi3DLa ] [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-11 15:32:15,005 ERROR: Unhandled Exception: 41002 appid missing, hints: [ req_id: PhfBwqLnRa-O0gZNa ] [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-16 18:48:48,385 ERROR: Unhandled Exception: global name 'wechat' is not defined [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
2019-04-16 18:49:34,031 ERROR: Unhandled Exception: global name 'wechat' is not defined [in /home/cry/PycharmProjects/ns-gas/main/router/__init__.py:14]
